### ISSUE TITLE
sesearch -T / --type is not backwards compatible

### ISSUE THREAD

**Issue by vmojzis** [SELinuxProject/setools#24]
In setools 3, sesearch had --type parameter with the following meaning:

       -T, --type
              Search for type_transition, type_member, and type_change rules.

which changed in setools 4 to:

       -T, --type_trans
              Find type_transition rules.

       --type_member
              Find type_member rules.

       --type_change
              Find type_change rules.

Changing the meaning of a flag like this can break user scripts.

I see two options of making the interface backwards compatible:

1) re-introducing --type as an alias to all 3 options

2) doing (1) and changing the meaning of -T yet again to mean --type

Where (1) should be safe to do, but (2) would break the current interface yet again (but it is a more complete solution).

What are your thoughts on this? 
I'd be happy to make the changes if you'd be willing to accept them.

**Comment by pebenito** [comment]
SETools 4.0 was a major release. This was an intentional choice to break backwards compatibility and change the options to how they are today. Since it has been 3 years since SETools 4.0 came out and this is the first time I'm aware of anyone complaining, I think this choice has had negligible impact.
